# 开发环境配置
server:
  port: 8080
  servlet:
    context-path: /api

spring:
  # 数据源配置
  datasource:
    druid:
      # 开发环境数据库配置
      url: jdbc:mysql://localhost:3306/common_admin_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: root
      password: 123456
      # 开发环境开启SQL监控
      filters: stat,wall,slf4j
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin123
        allow: 127.0.0.1,192.168.0.0/16

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0

  # 邮件配置(开发环境)
  mail:
    host: smtp.qq.com
    username: dev@example.com
    password: dev-password
    port: 587

  # 开发工具配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
    livereload:
      enabled: true
      port: 35729

# MyBatis Plus配置
mybatis-plus:
  configuration:
    # 开发环境开启SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 日志配置
logging:
  level:
    com.common: debug
    org.springframework.security: debug
    org.springframework.web: debug
    com.baomidou.mybatisplus: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

# Sa-Token配置
sa-token:
  # 开发环境token有效期设置短一些方便测试
  timeout: 7200
  # 开发环境输出详细日志
  is-log: true

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-version: true
    enable-reload-cache-parameter: true
    enable-after-script: true
    enable-filter-multipart-apis: false
    enable-filter-multipart-api-method-type: POST
    enable-request-cache: true
    enable-host-text: localhost:8080

# 系统配置(开发环境)
common:
  # 开发环境文件上传路径
  upload-path: D:/temp/upload/
  avatar-path: D:/temp/avatar/
  # 开启验证码
  captcha-enabled: false
  # 开发环境配置
  dev-mode: true
  # 允许的跨域源
  cors-origins: 
    - http://localhost:3000
    - http://localhost:8000
    - http://127.0.0.1:3000
    - http://127.0.0.1:8000